// Copyright (c) 2026 Snizyx Software LLC. All rights reserved.
// SPDX-License-Identifier: NCSA

package locale

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
)

var update = flag.Bool("update", false, "regenerate testdata/conformance/locale_match.json from this implementation")

// goldenPrefs are the preference lists whose matching results the Python runtime must reproduce.
var goldenPrefs = [][]string{
	{"ja"}, {"ja-JP"}, {"ja-Hira"}, {"en"}, {"en-US"}, {"en-GB"}, {"en-AU"}, {"en-US", "ja-JP"}, {"en-GB", "fr"},
	{"it-IT"}, {"it-IT", "fr-CA"}, {"fr"}, {"fr-CA"}, {"fr-CH", "de-CH"},
	{"es"}, {"es-ES"}, {"es-MX"}, {"es-419"}, {"es-US"},
	{"de"}, {"de-AT"}, {"de-CH"}, {"de", "ja"}, {"xx", "ja"}, {"xx-YY"},
	{"zh"}, {"zh-CN"}, {"zh-SG"}, {"zh-TW"}, {"zh-HK"}, {"zh-MO"}, {"zh-Hans"}, {"zh-Hant"}, {"zh-Hans-CN"}, {"zh-Hant-TW"}, {"zh-Hans-CN", "en"}, {"yue"},
	{"pt"}, {"pt-BR"}, {"pt-PT"}, {"pt-AO"},
	{"ko"}, {"ko-KR"},
	{"sr"}, {"sr-Latn"}, {"sr-Cyrl"}, {"sr-RS"}, {"sr-Latn-RS"}, {"sh"}, {"hr"}, {"bs"},
	{"iw"}, {"he"}, {"in"}, {"id"}, {"tl"}, {"fil"}, {"no"}, {"nb"}, {"nn"},
	{"not a tag"}, {""}, {"C"}, {"POSIX"}, {"ja_JP"}, {"JA-jp"}, {"zh-hant-tw"},
}

var goldenAvailable = [][]string{
	{"ja", "zh-Hans", "ko", "es", "fr", "de", "pt-BR"},
	{"zh-Hant"},
	{"pt"},
	{"sr-Latn", "sr-Cyrl"},
	{"en-GB", "fr"},
	{"nb", "he"},
}

type goldenFile struct {
	Description string        `json:"description"`
	Groups      []goldenGroup `json:"groups"`
}

type goldenGroup struct {
	Available []string     `json:"available"`
	Cases     []goldenCase `json:"cases"`
}

type goldenCase struct {
	Prefs []string `json:"prefs"`
	Want  string   `json:"want"`
}

func goldenPath() string {
	return filepath.Join("..", "..", "testdata", "conformance", "locale_match.json")
}

func generateGolden() goldenFile {
	f := goldenFile{Description: "Language matching: the catalog that Match selects for each preference list, or \"\" for English. Generated by the Go implementation (go test ./internal/locale -run Golden -update)."}
	for _, avail := range goldenAvailable {
		g := goldenGroup{Available: avail}
		for _, prefs := range goldenPrefs {
			g.Cases = append(g.Cases, goldenCase{Prefs: prefs, Want: Match(prefs, avail)})
		}
		f.Groups = append(f.Groups, g)
	}
	return f
}

// TestGolden keeps locale_match.json in step with the Go matcher; the Python runtime checks its own
// matcher against the same file.
func TestGolden(t *testing.T) {
	want := generateGolden()
	data, err := json.MarshalIndent(want, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	data = append(data, '\n')
	if *update {
		if err := os.WriteFile(goldenPath(), data, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	have, err := os.ReadFile(goldenPath())
	if err != nil {
		t.Fatalf("%v (run with -update to generate)", err)
	}
	if !bytes.Equal(have, data) {
		t.Fatalf("%s is out of date: run go test ./internal/locale -run Golden -update", goldenPath())
	}
}
